In [1]:
import sys
sys.path.insert(0, "C:/Users/marc-/IASD/Monte Carlo/Connect4Project")

In [2]:
from src.game.board import Board
from src.game.fight import fight
from src.common.constants import * 
import numpy as np

In [3]:
board = Board()

In [ ]:
board.playout(verbose=True)

In [ ]:
move = board.flat_mc()

In [ ]:
move.render()

In [4]:
fight("flat_mc", "manual_move", nb_playouts=4000)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
Turn 2
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 2 0 0 0]]
Turn 1
In which column do you want to insert your token ?3
Let's do that
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 2 1 0 0]]
Turn 2
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 2 1 0 0]]
Turn 1
In which column do you want to insert your token ?1
Let's do that
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 2 0 0 0]
 [0 1 2 1 0 0]]
Turn 2
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 2 0 0 0]
 [0 1 2 1 0 0]]
Turn 1
In which column do you want to insert your token ?2
Let's do that
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 2 0 0 0]
 [0 0 2 0 0 0]
 [0 1 2 1 0 0]]
Turn 2
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 2 0 0 0]
 [0 0 2 2 0 0]
 [0 1 2 1 0 0]]
Turn 1
In which column do

2